apiVersion: v2
name: task
description: A Helm chart for deploying the Task application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - task
  - application
maintainers:
  - name: Yuvraj Yadav
    email: evalsocket@gmail.com
dependencies:
  - name: postgresql
    alias: postgresql
    version: "*"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
